name: userbot
services:
  postgres:
    restart: always
    image: postgres:17
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-U', '${DB_USER}']
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'

  userbot:
    restart: always
    build:
      context: .
    environment:
      - DB_HOST=postgres
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-volume:
