version: '3.8'

services:

    userbot:
        image: ctrlfdocker/userbot:latest
        container_name: UserBot
        restart: on-failure
        env_file:
            - ../config/bot.env
        volumes:
            - ../config/reactionRoleConfig.json:/usr/src/app/config/reactionRoleConfig.json
            - ../config/banEmotesAtJoin.json:/usr/src/app/config/banEmotesAtJoin.json
            - ../forms/:/usr/src/app/forms/
