version: '3.8'

services:

    le-bot-en-js:
        image: tanguychiffoleau/le-bot-en-js:latest
        container_name: le-bot-en-js
        restart: on-failure
        env_file:
            - ../config/bot.env
        volumes:
            - ../config/reactionRoleConfig.json:/usr/src/app/config/reactionRoleConfig.json
