name: CD

on:
  release:
    types: [published]

jobs:
  build_and_push:
    name: Build and push OCI image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'

      - name: Build and push as tag
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 'ctrlfdocker/infra-bot:${{ github.event.release.tag_name }}'

      - name: Push as latest
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ctrlfdocker/infra-bot:latest

  pull:
    name: Pull the image and restart the container
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            curl -H "Authorization: Bearer ${{ secrets.WATCHTOWER_API_TOKEN }}" localhost:8080/v1/update