name: CI

on:
    pull_request:
        paths:
            - '**/*.js'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Uses Node.js 17.3.1
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: 17.3.1
            - run: npm ci
            - run: npm test
