name: CI

on:
    pull_request:
        paths:
            - '**/*.js'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Uses Node.js 14.16.0
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: 14.16.0
            - run: npm ci
            - run: npm test
