name: CD
on:
  push:
    branches: [master]
    tags: "*.*.*"
    paths:
      - 'src/*' 
  pull_request:
    branches: [master]
    tags: "*.*.*"
    paths:
      - 'src/*'

jobs:
  push_image_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tanguychiffoleau/le-bot-en-js
          tag_with_ref: true

  ssh:
    name: Pulls latest docker image and start up a new container
    runs-on: ubuntu-latest
    needs: push_image_to_docker_hub
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          docker pull tanguychiffoleau/le-bot-en-js:latest
          docker-compose up
